<a href="https://colab.research.google.com/github/praveenjittuga/ML-lab/blob/master/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


diff b/w list and numpy array lsit can store different type of data that is [int,float,string]. arrray can store same daya type of data that is [1,2,3,4]


In [2]:
a = np.array([[3,6,9,12],[15,18,21,24]],dtype="int")
a/3

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [3]:
list1 = [2,4,6,8]
list1/2

TypeError: ignored

In [4]:
a=np.arange((10),dtype="int")
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

two dimensional array below ex

In [6]:
a = np.array([[1,2],[2,3]])
a

array([[1, 2],
       [2, 3]])

two dimensional array using tuple

In [7]:
a = np.array(((1,2),(2,3)))
a

array([[1, 2],
       [2, 3]])

in below example mention the type of data that is int,float,complex....

In [8]:
a=np.array([2,3],dtype="complex")
print(a)

[2.+0.j 3.+0.j]


in below example mention ndmin that is ndimensinoal array below exmple output is two dimensional array i mention the ndmin=2 i.e two dimensional... array

In [9]:
a=np.array([1,2,3,4],ndmin=2,dtype="complex")
print(a)

[[1.+0.j 2.+0.j 3.+0.j 4.+0.j]]


In [10]:
a = np.array([[1,2,3],[4,5,6],[4,8,9]])
a.shape

(3, 3)

In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]],order="c")
a.shape=(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a=np.arange(24)
b=a.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

arange() creates an array of evenly spaced values...

In [13]:
a = np.arange(1,10,2 )
a

array([1, 3, 5, 7, 9])

In [14]:
a = np.arange(20,dtype="complex")
a

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [15]:
a = np.array(((1,2),(2,2)))
a

array([[1, 2],
       [2, 2]])

zero() creates array filled with 0s

In [16]:
np.zeros((3,4),dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

ones() creates array filled with ones..

In [17]:
np.ones((3,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

linspace() creates array filled evenly spaced values....

In [18]:
a = np.linspace(5,100,num=5,dtype="int",endpoint="false")
a

array([  5,  28,  52,  76, 100])

In [19]:
a = np.linspace(1,1000,dtype="int",num=50)
a

array([   1,   21,   41,   62,   82,  102,  123,  143,  164,  184,  204,
        225,  245,  266,  286,  306,  327,  347,  367,  388,  408,  429,
        449,  469,  490,  510,  531,  551,  571,  592,  612,  633,  653,
        673,  694,  714,  734,  755,  775,  796,  816,  836,  857,  877,
        898,  918,  938,  959,  979, 1000])

Linspace() if not mention the num parameter in linspace consider has default num in the example below..

In [20]:
a = np.linspace(1,10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

eye() return ndarray(n,m) here n is for rows and m is for coloumns identity() it is similar to eye()function. The identity array is a sqare array.

In [21]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [22]:
np.identity(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

random() rand() uniformly distributed values

In [23]:
np.random.rand(5,2)

array([[0.2856483 , 0.7083231 ],
       [0.68421049, 0.44360466],
       [0.74537777, 0.00375155],
       [0.11789158, 0.18769714],
       [0.90547076, 0.9111055 ]])

randn() normaly distributed values

In [24]:
np.random.randn(5,4)

array([[ 6.78511242e-01,  4.82186098e-01,  7.76196673e-01,
        -1.20530330e-03],
       [ 2.48513632e-01, -2.78063531e-01, -3.20631640e-01,
        -6.93065411e-01],
       [ 1.42639397e+00,  6.38086794e-01, -2.76692758e-01,
        -1.62899885e+00],
       [ 2.98574553e-01,  1.38743106e-01, -2.04914637e+00,
         1.42771777e+00],
       [ 1.07825646e+00, -6.62651228e-02, -3.04815170e-01,
        -6.40788624e-01]])

randint() uniformly distributed integers in a given range

In [25]:
np.random.randint(10,size=5)

array([7, 4, 7, 9, 3])

In [26]:
np.random.randint(2,5,size=(2,5))

array([[4, 3, 2, 4, 4],
       [3, 2, 2, 3, 4]])

randf() uniformly distributed floating point

In [27]:
np.random.ranf(5)

array([0.25844512, 0.7065191 , 0.26072965, 0.61185801, 0.06769509])